import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getDatabase, onValue, ref, runTransaction } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js';
import { firebaseConfig } from './firebase-config.js';

const ROOM_KEY = 'vocab-bright-room-v1';
const firebaseApp = initializeApp(firebaseConfig);
const database = getDatabase(firebaseApp);
const roomRef = ref(database, 'vocab_rooms/room603/state');
const GROUPS = 7;
const lesson = {id:'l2', title:'六年級國語 L2', words:[
 {char:'裁',terms:[['裁縫','裁剪並縫製衣服，或指從事這種工作的人。'],['裁員','因業務縮減而減少工作人員。'],['裁判','體育比賽中負責評判勝負的司法人员。'],['體裁','詩歌、散文、小說等文章的寫作樣式或結構。'],['獨裁','獨自掌握政治權力，實行專制統治。'],['獨出心裁','比喻構思獨特，與眾不同。']]},
 {char:'茂',terms:[['茂盛','植物生長繁茂。'],['豐茂','形容土地肥沃，草木生長旺盛。'],['根深葉茂','植物根基深、枝葉茂密。'],['聲情並茂','演唱、朗誦或演說時聲音和感情生動感人。'],['圖文並茂','書籍、報告或海報中圖畫與文字都很豐富精采。']]},
 {char:'藤',terms:[['藤蔓','藤本植物攀爬蔓延的細莖。'],['藤椅','用藤條編織成的椅子，通風涼快。'],['紫藤','春季開紫藍色花的蔓生植物。'],['蔓藤','植物細長且攀附他物的莖。'],['順藤摸瓜','比喻沿著線索追根究底，查明事實真相。']]},
 {char:'免',terms:[['避免','防止、設法使不發生。'],['免稅','免除應繳納的稅金。'],['免除','省去、撤除。'],['免費','不收取費用。'],['在所難免','無論如何很難免除、避免。']]}
]};
function baseState(){return {command:'waiting',wordIndex:0,duration:60,endsAt:null,presence:{},answers:{},updatedAt:Date.now()}}
let roomState=(()=>{try{return JSON.parse(localStorage.getItem(ROOM_KEY))||baseState()}catch{return baseState()}})();
function read(){return structuredClone(roomState)}
function notify(){localStorage.setItem(ROOM_KEY,JSON.stringify(roomState));if(channel)channel.postMessage(roomState);window.dispatchEvent(new Event('roomchange'))}
function write(next){next.updatedAt=Date.now();roomState=next;notify();runTransaction(roomRef,current=>{const prior=current||baseState();const shouldClearAnswers=(next.command==='waiting'||next.command==='stopped'||(next.command==='playing'&&Object.keys(next.answers||{}).length===0))&&Object.keys(next.answers||{}).length===0;return {...prior,...next,presence:{...(prior.presence||{}),...(next.presence||{})},answers:shouldClearAnswers?{}:{...(prior.answers||{}),...(next.answers||{})}}}).catch(()=>{document.querySelectorAll('.cloud-status').forEach(el=>el.textContent='● Firebase 連線失敗，使用本機暫存')})}
const channel='BroadcastChannel' in window?new BroadcastChannel(ROOM_KEY):null;
channel?.addEventListener('message',()=>window.dispatchEvent(new Event('roomchange')));
window.addEventListener('storage',e=>{if(e.key===ROOM_KEY)window.dispatchEvent(new Event('roomchange'))});
onValue(roomRef,snapshot=>{roomState={...baseState(),...(snapshot.val()||{})};notify();document.querySelectorAll('.cloud-status').forEach(el=>el.textContent='● Firebase 即時同步已連線')},()=>{document.querySelectorAll('.cloud-status').forEach(el=>el.textContent='● Firebase 連線失敗，使用本機暫存')});
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function seconds(s){if(!s||s<0)return '--:--';return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.ceil(s%60)).padStart(2,'0')}`}
function activeWord(state){return lesson.words[state.wordIndex]||lesson.words[0]}
if(document.body.dataset.page==='teacher')teacherApp(); else if(document.body.dataset.page==='student')studentApp();
function teacherApp(){const teacherLogin=document.querySelector('#teacherLogin'),teacherLoginForm=document.querySelector('#teacherLoginForm'),teacherPassword=document.querySelector('#teacherPassword'),loginError=document.querySelector('#loginError');if(sessionStorage.getItem('vocab-teacher-authorized')!=='yes'){teacherLogin.showModal();teacherLoginForm.onsubmit=e=>{e.preventDefault();if(teacherPassword.value==='0603'){sessionStorage.setItem('vocab-teacher-authorized','yes');teacherLogin.close()}else{loginError.textContent='密碼不正確，請再試一次。';teacherPassword.select()}}}const lessonSelect=document.querySelector('#lessonSelect'),wordSelect=document.querySelector('#wordSelect'),timeSelect=document.querySelector('#timeSelect');lessonSelect.innerHTML=`<option>${lesson.title}</option>`;function populate(){wordSelect.innerHTML=lesson.words.map((w,i)=>`<option value="${i}">【${w.char}】字生字配對</option>`).join('');const s=read();wordSelect.value=s.wordIndex;timeSelect.value=s.duration}populate();
 const importDialog=document.querySelector('#importDialog'),pdfInput=document.querySelector('#pdfInput'),pdfName=document.querySelector('#pdfName'),importName=document.querySelector('#importLessonName'),createImport=document.querySelector('#createImportBtn'),importReview=document.querySelector('#importReview'),importReviewTitle=document.querySelector('#importReviewTitle'),importReviewStatus=document.querySelector('#importReviewStatus'),extractedWords=document.querySelector('#extractedWords'),extractedText=document.querySelector('#extractedText');document.querySelector('#importBtn').onclick=()=>importDialog.showModal();pdfInput.onchange=()=>{const file=pdfInput.files?.[0];pdfName.textContent=file?`已選擇：${file.name}`:'尚未選擇檔案';createImport.disabled=!file;if(file&&!importName.value)importName.value=file.name.replace(/\.pdf$/i,'')};createImport.onclick=async()=>{const file=pdfInput.files?.[0];if(!file)return;const name=importName.value||file.name.replace(/\.pdf$/i,'');localStorage.setItem('vocab-pending-pdf-import',JSON.stringify({fileName:file.name,lessonName:name,createdAt:Date.now()}));importDialog.close();importReview.hidden=false;importReviewTitle.textContent=name;importReviewStatus.textContent='正在從 PDF 擷取文字…';extractedWords.innerHTML='';extractedText.value='';try{const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let text='';for(let pageNo=1;pageNo<=pdf.numPages;pageNo++){const page=await pdf.getPage(pageNo),content=await page.getTextContent();text+=content.items.map(item=>item.str).join(' ')+'\n'}extractedText.value=text;const parts=text.split(/生字\s*[：:]/).slice(1);const chars=parts.map(part=>part.trim().slice(0,1)).filter(char=>/^[\u3400-\u9fff]$/.test(char));const unique=[...new Set(chars)];extractedWords.innerHTML=unique.length?unique.map(char=>`<article class="extracted-word"><strong>${char}</strong><p>已偵測生字；請開啟下方文字確認語詞與詞義。</p></article>`).join(''):'<p class="muted">尚未辨識到固定格式生字，請在下方文字區校對或手動輸入。</p>';importReviewStatus.textContent=`已完成 ${pdf.numPages} 頁文字擷取，偵測到 ${unique.length} 個生字。`;}catch(error){importReviewStatus.textContent='此 PDF 無法自動擷取文字（可能為掃描檔或網路未連線）。請在下方貼上文字後校對。';}importReview.scrollIntoView({behavior:'smooth',block:'start'})};document.querySelector('#saveImportBtn').onclick=()=>{localStorage.setItem('vocab-imported-text',extractedText.value);alert('已儲存校對內容。下一步會將校對資料轉成可派送的生字題庫。')};
 document.querySelector('#startBtn').onclick=()=>{const s=read();s.wordIndex=+wordSelect.value;s.duration=+timeSelect.value;s.command='playing';s.endsAt=Date.now()+s.duration*1000;s.answers={};write(s)};
 document.querySelector('#stopBtn').onclick=()=>{const s=read();s.command='stopped';s.endsAt=null;write(s)};
 document.querySelector('#resetBtn').onclick=()=>{const s=read();s.command='waiting';s.endsAt=null;s.answers={};write(s)};
 function render(){const s=read(),w=activeWord(s),left=Math.max(0,((s.endsAt||0)-Date.now())/1000);document.querySelector('#countdown').textContent=seconds(s.command==='playing'?left:null);document.querySelector('#reviewTitle').textContent=s.command==='waiting'?'等待派送任務':`【${w.char}】字全班作答結果與檢討`;document.querySelector('#reviewSub').textContent=s.command==='playing'?'學生正在作答，結果會即時更新。':s.command==='stopped'?'本輪已結束，可檢視各組作答。':'先選擇生字與時間，再發布任務。';
 document.querySelector('#presence').innerHTML=Array.from({length:GROUPS},(_,i)=>{const id=i+1,on=s.presence[id]&&Date.now()-s.presence[id]<16000;return `<span class="presence-chip ${on?'online':''}">第 ${id} 組 ${on?'● 已連線':'○ 未連線'}</span>`}).join('');
 const results=Object.values(s.answers);const errors={};results.forEach(a=>a.wrong?.forEach(x=>errors[x]=(errors[x]||0)+1));const top=Object.entries(errors).sort((a,b)=>b[1]-a[1])[0];document.querySelector('#insight').innerHTML=top?`<span>🔥</span><div><strong>課堂核心檢討標的：【${top[0]}】</strong><p>已有 ${top[1]} 組在此詞語配對發生迷思，可立即帶全班辨析。</p></div>`:`<span>🔎</span><div><strong>課堂檢討提示</strong><p>開始後，系統會自動整理最常被混淆的語詞。</p></div>`;
 document.querySelector('#groupGrid').innerHTML=Array.from({length:GROUPS},(_,i)=>{const id=i+1,a=s.answers[id],on=s.presence[id]&&Date.now()-s.presence[id]<16000;return `<article class="group-card ${on?'online':''}"><h3>第 ${id} 組</h3>${a?`<p class="group-state">${a.complete?'✅ 已完成':'✏️ 作答中'} · 正確 ${a.correct}/${w.terms.length}</p><ul class="answer-list">${a.wrong?.length?a.wrong.map(x=>`<li class="wrong">✕ ${x}</li>`).join(''):'<li>目前沒有錯誤配對</li>'}</ul>`:`<p class="group-state">${on?'已加入房間，等待作答。':'尚未連線'}</p>`}</article>`}).join('')}
 window.addEventListener('roomchange',render);setInterval(render,500);render()}
function studentApp(){let group=+localStorage.getItem('vocab-group')||0,selected=null,termOrder=[];const dialog=document.querySelector('#groupDialog');document.querySelector('#groupChoices').innerHTML=Array.from({length:GROUPS},(_,i)=>`<button class="group-choice" value="${i+1}">第 ${i+1} 組</button>`).join('');document.querySelectorAll('.group-choice').forEach(b=>b.onclick=()=>{group=+b.value;localStorage.setItem('vocab-group',group);dialog.close();presence();render()});if(!group)dialog.showModal();
 function presence(){if(!group)return;const s=read();s.presence[group]=Date.now();write(s)} setInterval(presence,5000);presence();
 function render(){const s=read(),w=activeWord(s),playing=s.command==='playing'&&Date.now()<(s.endsAt||0);document.querySelector('#studentStatus').textContent=group?`● 第 ${group} 組已連線`:'● 等待加入小組';document.querySelector('#wordChips').innerHTML=lesson.words.map((x,i)=>`<span class="word-chip ${i===s.wordIndex?'active':''}">${x.char}</span>`).join('');document.querySelector('#charBadge').textContent=w.char;document.querySelector('#studentTimer').textContent=seconds(playing?(s.endsAt-Date.now())/1000:null);document.querySelector('#taskPanel').classList.toggle('locked',!playing);document.querySelector('#taskTitle').textContent=playing?`【第 ${group} 組】生字【${w.char}】配對任務`:(s.command==='stopped'?'本輪作答已結束':'已進入房間，等待老師開始');document.querySelector('#taskHint').textContent=playing?'請將左側語詞與右側詞義配對。':'請留意教師大螢幕，老師發布後會自動開始。';if(!termOrder.length||termOrder[0]?.word!==w.char){termOrder=shuffle(w.terms.map(([term,meaning])=>({word:w.char,term,meaning})));selected=null}drawCards(s,w,playing)}
 function drawCards(s,w,playing){const prior=s.answers[group]||{matches:{},wrong:[]};const left=w.terms.map(([term,meaning])=>({term,meaning})),right=termOrder;document.querySelector('#matchingGrid').innerHTML=`<div>${left.map(x=>card(x.term,'term',prior.matches[x.term])).join('')}</div><div>${right.map(x=>card(x.meaning,'meaning',null)).join('')}</div>`;document.querySelectorAll('.match-card').forEach(b=>b.onclick=()=>choose(b.dataset.value,b.dataset.type));function card(value,type,matched){const isMatched=matched==='ok';return `<button class="match-card ${selected?.type===type&&selected.value===value?'selected':''} ${isMatched?'matched':''}" data-type="${type}" data-value="${value.replaceAll('&','&amp;').replaceAll('"','&quot;')}">${value}${isMatched?'　✓':''}</button>`}}
 function choose(value,type){const s=read(),w=activeWord(s);if(s.command!=='playing')return;if(!selected){selected={value,type};render();return}if(selected.type===type){selected={value,type};render();return}const term=selected.type==='term'?selected.value:value,meaning=selected.type==='meaning'?selected.value:value;const correct=w.terms.find(x=>x[0]===term)?.[1]===meaning;const a=s.answers[group]||{matches:{},wrong:[],complete:false,correct:0};if(correct){a.matches[term]='ok';a.correct=Object.keys(a.matches).length;document.querySelector('#feedback').textContent='配對正確！';}else{if(!a.wrong.includes(term))a.wrong.push(term);document.querySelector('#feedback').textContent='再想一想，試著選另一張詞義卡。'}a.complete=a.correct===w.terms.length;s.answers[group]=a;write(s);selected=null;render()}
 window.addEventListener('roomchange',render);setInterval(render,500);render()}
